---
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    # ignore:
    #   - goos: darwin
    #     goarch: "386"
    #   - goos: darwin
    #     goarch: "arm64"
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
   - format: binary
     name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
nfpms:
  - formats:
      - deb
      - rpm
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
changelog:
  skip: true
