---
version: 2
project_name: vmrss

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
release:
  draft: false
changelog:
  disable: true
nfpms:
  - package_name: "vmrss"
    maintainer: rwxd <git@rwxd.de>
    description: "Simple tool to show the memory usage of a process and its children"
    formats:
      - deb
      - rpm
